version: "3.8"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    networks:
      - topgeschenken

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - topgeschenken

  db:
    image: postgres
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - topgeschenken

  test_db:
    image: postgres
    environment:
      POSTGRES_DB: symfony_test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - topgeschenken

  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      # URL: http://localhost:8080/api/doc.json
      SWAGGER_JSON: /var/www/html/api/doc.json
    volumes:
      - .:/var/www/html
    ports:
      - "8081:8080"
    depends_on:
      - nginx
    networks:
      - topgeschenken

networks:
  topgeschenken:
    driver: bridge
