nelmio_api_doc:
  documentation:
    info:
      title: Customer api
      description: Top Regalitos Assesment Api
      version: 1.0.0
  areas: # to filter documented areas
    path_patterns:
      - ^/(?!/doc$) # Accepts routes under /api except /api/doc
